cosi-project/runtime

- .codecov.yml
- .dockerignore
- .drone.yml
- .gitignore
- .golangci.yml
- .kres.yaml
- .markdownlint.json
- Dockerfile
- LICENSE
- Makefile
- README.md
- cmd/directory-fun/main.go
- cmd/directory-fun/path.go
- go.mod
- go.sum
- hack/git-chglog/CHANGELOG.tpl.md
- hack/git-chglog/config.yaml
- hack/release.sh
- pkg/resource/null.go
- pkg/resource/resource.go
- pkg/resource/resource_test.go
- pkg/state/condition.go
- pkg/state/errors.go
- pkg/state/impl/local/collection.go
- pkg/state/impl/local/errors.go
- pkg/state/impl/local/errors_test.go
- pkg/state/impl/local/local.go
- pkg/state/impl/local/local_test.go
- pkg/state/state.go
- pkg/state/wrap.go
> feat: initial version of the runtime based on the state

- .github/dependabot.yml
- .github/workflows/ci.yml
> test: add GitHub actions flow

- .github/workflows/ci.yml
This allows manual trigger of CI.
Signed-off-by: Andrew Rynhard <andrew@rynhard.io>
> chore: add workflow_dispatch to GH actions

- .conform.yaml
- .drone.yml
- Dockerfile
- Makefile
- hack/release.sh
- hack/release.toml
> chore: re-run kres

- pkg/controller/conformance/controllers.go
- pkg/controller/conformance/resources.go
- pkg/controller/conformance/runtime.go
- pkg/controller/protobuf/client/client.go
- pkg/controller/protobuf/protobuf_test.go
- pkg/controller/protobuf/server/server.go
- pkg/controller/runtime/dependency/database.go
- pkg/controller/runtime/runtime.go
- pkg/resource/metadata_test.go
- pkg/resource/phase.go
- pkg/state/conformance/state.go
- pkg/state/protobuf/client/client.go
- pkg/state/protobuf/protobuf_test.go
> chore: fix nolint directives

- .conform.yaml
- .dockerignore
- .drone.yml
- .golangci.yml
- Dockerfile
- Makefile
- go.mod
- hack/release.sh
- pkg/controller/conformance/controllers.go
- pkg/controller/conformance/resources.go
- pkg/controller/conformance/runtime.go
- pkg/controller/protobuf/client/client.go
- pkg/controller/protobuf/server/server.go
- pkg/controller/runtime/adapter.go
- pkg/controller/runtime/runtime.go
- pkg/resource/any.go
- pkg/resource/meta/namespace.go
- pkg/resource/meta/resource_definition.go
- pkg/resource/metadata_test.go
- pkg/resource/protobuf/registry.go
- pkg/resource/protobuf/resource.go
- pkg/resource/tombstone.go
- pkg/state/conformance/resources.go
- pkg/state/filter.go
- pkg/state/impl/inmem/build.go
- pkg/state/impl/inmem/collection.go
- pkg/state/impl/inmem/inmem.go
- pkg/state/impl/namespaced/namespaced.go
- pkg/state/protobuf/client/client.go
- pkg/state/wrap.go
Bump kres to latest version and regenerate stuff.
> chore: bump to latest kres version

- Dockerfile
- Makefile
- pkg/resource/typed/typed_resource.go
- pkg/resource/typed/types_resource_test.go
Add TypedResource type and tests for it
> chore: add typed resource

- .github/dependabot.yml
- .github/workflows/codeql-analysis.yml
Also enable Dependabot for `go.mod`.
> chore: enable CodeQL analysis

- go.mod
- go.sum
Update go yaml to the latest version.
> chore: update go-yaml

- .drone.yml
- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
> chore: fix up CI instructions for branch 'main'

- go.mod
- go.sum
Get fixes and changes from the latest version.
> chore: bump github.com/siderolabs/protoenc to 0.2.0

- pkg/controller/runtime/runtime_test.go
- pkg/state/impl/inmem/collection.go
- pkg/state/impl/inmem/local_test.go
Also report an error for `Watch` in addition to `WatchKind`.
> fix: report detailed error on buffer overrun

- pkg/state/impl/inmem/collection.go
Now `WatchKind` for in-memory implementation captures as many events as there are available in the event stream for any mutex lock-unlock cycle.
This helps to speed up event delivery when there are many outstanding events in the queue while there is high ingestion rate of new events.
It also reduces mutex contention (less lock/unlocks per resource update).
> fix: send as many events as possible from one mutex lock

- pkg/resource/rtestutils/destroy.go
Those two functions enable actions after we initiated `Teardown` on the resource, but before we wait and destroy it. Useful for resources with finalizers.
> chore: add `BeginDestroyAll` and `BeginDestroy` functions.

- pkg/controller/generic/transform/controller.go
- pkg/controller/generic/transform/transform_test.go
The problem is triggered with the following flow: let's image transform controller maps resources A to resources B keeping ID the same.
1. A(1) is created.
2. Transform controller creates output B(1).
3. Something sets a finalizer on B(1).
4. A(1) is destroyed.
5. Transform controller can't destroy B(1), as it has a finalizer set, but it puts B(1) into tearing down phase.
6. A(1) is re-created (that is essentially new A(1)).
7. Transform controller can't update B(1), as it's being torn down.
8. Finalizer from B(1) is removed.
9. Transform controller still can't move on.
Before the fix controller will be "stuck" at the step (9), while with the fix controller will first destroy tearing down B(1), and then re-create it from new A(1).
Signed-off-by: Andrey Smirnov …
> fix: always destroy tearing down outputs

- pkg/resource/rtestutils/destroy.go
We can `Teardown` the resource as many times as we want, so there is no reason to split original function into beginning and continuation parts.
> chore: remove BeginDestroy and add Teardown

- pkg/resource/rtestutils/destroy.go
This shows up if there are multiple teardown/destroy sequences concurrently for the same resource type: `Destroy` might pick up a resource with the ID not from the list and destroy it (or return earlier than it should).
> fix: ignore other resources in rtestutils.Destroy

- pkg/controller/generic/transform/controller.go
This is symmetric to the PR #226, but for finalizer removal func - if the controller creates some extra outputs, it should have a chance to clean them up as well.
> feat: allow finalizer removal func to write resources with extra outputs

- go.mod
- go.sum
- pkg/resource/rtestutils/assertions.go
This will allow us to customize Watch and List behavior. This PR introduces just one override - namespace.
> chore: add Options to AssertResources

- pkg/controller/conformance/resource.go
- pkg/controller/runtime/dependency/database.go
- pkg/controller/runtime/runtime.go
- pkg/resource/any.go
- pkg/resource/any_test.go
- pkg/resource/internal/kv/kv.go
- pkg/resource/metadata.go
- pkg/resource/protobuf/resource.go
- pkg/resource/protobuf/spec.go
- pkg/resource/resource.go
- pkg/resource/rtestutils/errors.go
- pkg/resource/tombstone.go
- pkg/resource/typed/typed_resource.go
- pkg/state/conformance/resources.go
- pkg/state/impl/inmem/collection.go
- Replace interface{} with any.
- Replace make(map[...]...) with map[...]...{}
> chore: code cleanup

- .drone.yml
- .golangci.yml
- Dockerfile
- Makefile
- go.mod
- go.sum
- run rekres
- github.com/stretchr/testify to v1.8.4
- github.com/cloudflare/circl to v1.3.3
> chore: bump deps

- pkg/controller/conformance/controllers.go
- pkg/controller/conformance/runtime.go
- pkg/controller/generic/transform/controller.go
- pkg/controller/generic/transform/transform_test.go
- pkg/controller/protobuf/client/client.go
- pkg/controller/protobuf/protobuf_test.go
- pkg/controller/runtime.go
- pkg/controller/runtime/adapter.go
- pkg/controller/runtime/runtime.go
- pkg/controller/runtime/tracking_pool.go
- pkg/safe/util.go
This allows to map only _some_ Inputs to Outputs.
Also add an automatic lightweight tracker to adapters.
> feat: allow TransformController to skip over some inputs

- pkg/controller/generic/transform/controller.go
- pkg/controller/generic/transform/options.go
- pkg/controller/generic/transform/transform_test.go
This will provide more flexibility in the transform controller usage.
> feat: support `OutputShared` for the main res in Transform controller

- pkg/resource/rtestutils/assertions.go
Add a watch-based assertion on the length of a resource list.
> test: add rtestutils.AssertLength

- pkg/resource/rtestutils/destroy.go
When something destroys resources concurrently while `Teardown` or `Destroy` is called, it might miss events or try to tear down removed resources.
> test: even more destroy fixes

- pkg/controller/generic/transform/controller.go
- pkg/controller/generic/transform/metrics.go
Measure number of cycles/items/busy time.
> chore: add TransformController specific metrics

- pkg/controller/generic/cleanup/cleanup.go
- pkg/controller/generic/cleanup/cleanup_test.go
If extra owners is passed, the controller will not skip the resources owned by the specified owners and will destroy them too.
> feat: allow extra owners in the cleanup controllers

- pkg/controller/generic/transform/controller.go
- pkg/controller/generic/transform/transform_test.go
Pre/post methods are called before and after the transform controller runs the loop over all processed resources.
> feat: implement pre/post transform hooks in the Transform controller

- pkg/controller/generic/qtransform/options.go
- pkg/controller/generic/qtransform/qtransform.go
- pkg/controller/generic/qtransform/qtransform_test.go
Add some generic commonly used mappers.
Implement support for ignoring teardown until other controllers did their job, and proceed to output teardown only then.
> feat: add some new settings for qtransform controller

- pkg/controller/runtime/internal/qruntime/qruntime.go
This logs each item being reconciled, both failures and successes.
It is questionable whether it's too much, but at least it should allow us to debug things way easier.
Sample:
```
ERROR   reconcile failed        {"controller": "QFailingController", "namespace": "q-fail-in", "type": "test/str", "id": "id1", "job": "reconcile", "error": "failing as requested", "interval": "373.67479ms", "busy": "29.626µs"}
INFO    reconcile succeeded     {"controller": "QFailingController", "namespace": "q-fail-in", "type": "test/str", "id": "id5", "job": "reconcile", "busy": "74.01µs"}
INFO    reconcile succeeded     {"controller": "QFailingController", "namespace": "q-fail-in", "type": "test/str", "id": "id3", "job": "reconcile", "busy": "32.501µs", "interval": "100ms", "requeued": true}
ERROR …
```
> feat: add more logging for qruntime controllers

- pkg/controller/runtime/internal/controllerstate/adapter.go
- pkg/controller/runtime/internal/qruntime/qruntime.go
- pkg/controller/runtime/internal/rruntime/rruntime.go
- pkg/controller/runtime/options/options.go
- pkg/controller/runtime/runtime_test.go
More of a debugging/tracing thing, not for production.
> chore: add an option to warn about uncached controller reads

- pkg/controller/generic/qtransform/options.go
Allow specifying the input type for extra qcontroller inputs, e.g., `DestroyReady`.
> feat: add a new utility method `qtransform.WithExtraInput`

- pkg/controller/conformance/qcontrollers.go
- pkg/controller/conformance/runtime.go
- pkg/controller/qcontroller.go
- pkg/controller/runtime/internal/qruntime/qruntime.go
This will allow running tasks which are not tied to the resource updates.
> feat: support run and shutdown hooks in the `QController`

- pkg/controller/generic/qtransform/qtransform.go
- pkg/controller/generic/qtransform/qtransform_test.go
Add a new tag called `DestroyOutputTag` that is similar to `SkipReconcileTag`, which destroys the output resource.
> feat: add an error tag to destroy outputs

- pkg/controller/runtime/internal/qruntime/qruntime.go
There were no checks on what map function returns as a result, which might lead to fun bugs when map function returns an input which is not an expected intput of the QController, and it's hard to track why it got into the queue.
This validation isn't strictly required by the runtime itself, but it might lead to hard to trace bugs for the users of the runtime.
> fix: validate QController mapped results

- pkg/controller/runtime/runtime.go
Fix data race:
```
==================
WARNING: DATA RACE
Read at 0x00c0008fe1e3 by goroutine 376:
testing.(*common).logDepth()
/usr/local/go/src/testing/testing.go:1023 +0x504
testing.(*common).log()
/usr/local/go/src/testing/testing.go:1010 +0xa4
.....
go.uber.org/zap.(*Logger).Debug()
/go/pkg/mod/go.uber.org/zap@v1.27.0/logger.go:239 +0x67
github.com/cosi-project/runtime/pkg/controller/runtime.(*Runtime).processEvents()
/go/pkg/mod/github.com/cosi-project/runtime@v0.4.6/pkg/controller/runtime/runtime.go:349 +0x5e4
github.com/cosi-project/runtime/pkg/controller/runtime.(*Runtime).deduplicateWatchEvents()
/go/pkg/mod/github.com/cosi-project/runtime@v0.4.6/pkg/controller/runtime/runtime.go:421 +0x51c
github.com/cosi-project/runtime/pkg/controller/runtime.(*Runtime).processWatched.gowrap1() …
```
> fix: replace naked `go` statements with errgroup

- .drone.yml
- Dockerfile
- pkg/controller/runtime/internal/cache/cache.go
- pkg/controller/runtime/internal/cache/state.go
- pkg/controller/runtime/runtime.go
- pkg/controller/runtime/runtime_test.go
Allow the consumer to take advantage of the cached state for Get/List operations.
> feat: export controller-runtime cached state

- pkg/safe/state.go
It should make it way easier to sort resource lists.
> feat: add safe.List.SortFunc

- pkg/state/conformance/state.go
It verifies that parallel destroy doesn't break underlying state implementations.
> test: add parallel destroy test to the conformance suite

- pkg/controller/conformance/controllers.go
- pkg/controller/generic/cleanup/cleanup.go
- pkg/controller/generic/transform/controller.go
- pkg/safe/state.go
> feat: use rangefunc for iterators

- pkg/controller/generic/qtransform/qtransform.go
- pkg/controller/generic/qtransform/qtransform_test.go
The recently added `IgnoreTeardownWhile` function to the QTransform controllers introduced a bug in the existing `IgnoreTeardownUntil` logic: we were wrongly short-circuiting in the finalizer check loop, causing the controller to run teardown prematurely.
Fix the logic and modify the `IgnoreTeardownUntil` test to catch the issue before the fix.
Thanks @Unix4ever for finding it.
> fix: fix the bug in `IgnoreTeardownUntil` logic

- pkg/resource/rtestutils/destroy.go
Teardown might fail with phase conflict if the `Teardown` was called in another process.
Just ignore that error, it means that teardown was already called.
> test: ignore phase conflict errors in the `rtestutils.Destory`
