- pkg/resource/any.go
- pkg/resource/any_test.go
This helps to preserve server-side YAML formatting when resource spec
goes through YAML marshaling (e.g. in the API).
> fix: preserve original YAML formatting in resource.Any

- go.mod
- go.sum
- pkg/controller/runtime/adapter.go
- pkg/controller/runtime/runtime.go
- pkg/controller/runtime/runtime_controllers_test.go
- pkg/controller/runtime/runtime_test.go
On controller failure new reconcile event is scheduler and controller is
restarted with exponential backoff to prevent crash looping.
Errors and restarts are logged for easier debugging.
> feat: restart failing controllers automatically with exp backoff

- pkg/state/conformance/state.go
- pkg/state/impl/inmem/collection.go
This fixes user-facing `talosctl get <resource>`, and also provides
stable order for controllers listing other resources.
This also aligns with the way etcd API works (returns sorted keys).
> feat: sort resources returned from the List() API

- pkg/state/conformance/state.go
- pkg/state/impl/inmem/collection.go
- pkg/state/impl/inmem/inmem.go
- pkg/state/impl/namespaced/namespaced.go
- pkg/state/options.go
- pkg/state/state.go
This allows to have a consistent view of a list of resources, it is
bootstrapped with the initial list and then incremental updates.
> feat: add an option to bootstrap WatchKind with initial list of resources

- pkg/state/state.go
Simple fix to allow easier printing of events.
> chore: provide fmt.Stringer for EventType

- go.mod
- go.sum
- pkg/resource/any.go
- pkg/resource/any_test.go
- pkg/resource/metadata_test.go
This should address incorrect comment indents as we're going to write
the spec as a raw YAML block.
Signed-off-by: Artem Chernyshev <artem.0xD2@gmail.com>
> feat: use go-yaml fork and serialize spec as RawYAML objects

- .drone.yml
- .github/workflows/ci.yml
- Dockerfile
- Makefile
- cmd/runtime/main.go
Since the runtime now lives under the COSI project, we don't need "cosi"
in the name. We also discussed the general practice of not using the
project name (COSI) in the implementation. This change renames
"cosi-runtime" to "runtime" to align the project with this decision.
Signed-off-by: Andrew Rynhard <andrew@rynhard.io>
> chore: rename cosi-runtime to runtime

- api/v1alpha1/resource.pb.go
- api/v1alpha1/runtime.pb.go
- api/v1alpha1/runtime_grpc.pb.go
- api/v1alpha1/state.pb.go
- api/v1alpha1/state_grpc.pb.go
- cmd/runtime/main.go
Signed-off-by: Andrew Rynhard <andrew@rynhard.io>
> feat: add flag to listen on TCP

- pkg/resource/meta/resource_definition.go
- pkg/resource/meta/resource_definition_test.go
- pkg/resource/meta/sensitivity.go
Sensitivity indicates how secret resource of this type is.
The empty value represents a non-sensitive resource.
> feat: add sensitivity to RDs

- pkg/state/impl/inmem/collection.go
- pkg/state/impl/inmem/inmem.go
- pkg/state/impl/inmem/options.go
- pkg/state/options.go
This reduce history depth from 1000 entries to 100 entries (for each
resource type under a namespace). The main benefit is memory savings.
Also gc unused and never implemented option.
> fix: make default resource watch history more shallow

- pkg/resource/meta/resource_definition.go
- pkg/resource/meta/resource_definition_test.go
Refactor ResourceDefinition so that `Aliases` contains non-trivial,
human readable important aliases.
> fix: print non-trivial resource definitions aliases in table output

- pkg/controller/conformance/controllers.go
- pkg/controller/conformance/resources.go
- pkg/resource/any.go
- pkg/resource/meta/namespace.go
- pkg/resource/meta/resource_definition.go
- pkg/resource/resource.go
- pkg/state/conformance/resources.go
- pkg/state/conformance/state.go
It is not being used almost anywhere, and implementing it for every
resource is a lot of routine work.
It is now implemented in a generic way as a `resource.String` function.
> refactor: remove fmt.Stringer from resource.Resource interface

- go.mod
- go.sum
- pkg/resource/metadata_test.go
Bump minimal Go version from 1.16 to 1.18
> Bump Go to 1.18

- pkg/resource/meta/namespace.go
- pkg/resource/meta/resource_definition.go
- pkg/resource/meta/sensitivity.go
- pkg/resource/meta/spec/resource_definition.go
- pkg/resource/meta/spec/sensitivity.go
- pkg/resource/typed/typed_resource.go
Refactor meta.Namespace and meta.ResourceDefinition by implementing them using typed.Resource and moving ResourceDefinitionSpec to a side pkg to prevent cyclic imports.
> chore: refactor namespace and resource_definition resources

- pkg/controller/conformance/resource.go
- pkg/controller/conformance/resources.go
Use generic Resource to implement this three types.
> chore: refactor IntResource, StrResource, SentenceResource using generics

- go.mod
- go.sum
- pkg/controller/runtime/adapter.go
- pkg/controller/runtime/dependency/database.go
- pkg/controller/runtime/dependency/database_test.go
- pkg/controller/runtime/dependency/dependency_test.go
- pkg/controller/runtime/runtime.go
- pkg/resource/version.go
- pkg/state/protobuf/client/client.go
Now that we have generics and require Go 1.18 - redo pointer.* functions as two generic functions.
> chore: migrate from AlekSi/pointer to siderolabs/go-pointer

- pkg/resource/protobuf/resource.go
- pkg/resource/typed/typed_resource.go
This implements a generic `UnmarshalProto` for `typed.Resource`.
There might be a better way to do protobuf marshaling with generics, but
this is a stopgap for now to allow conversion of the only resource in
Talos right now which implements conversion to protobufs.
> feat: implement generic UnmarshalProto on the resource

- pkg/resource/typed/typed_resource.go
This is better than using `reflect`.
Thanks to @DmitriyMV for the hint.
> refactor: use better version of dynamic type casting

- pkg/resource/protobuf/spec.go
- pkg/resource/protobuf/spec_test.go
The wrapper implements `DeepCopy`, `MarshalProto` and `UnmarshalProto`
methods and allows using protobuf generated structs in `typed` resources
which require specs to support passing by copy.
> feat: implement a generic `proto.Message` spec implementation

- pkg/resource/protobuf/spec.go
This is required for Theila internal logic as it relies on dumping
protobuf specs as `map[string]interface{}` and sending it to the
javascript side.
With the change it will be possible to extract value from the wrapper
without knowing an exact type.
> chore: provide an interface for getting wrapped protobuf value

- pkg/resource/protobuf/spec.go
It is not going to be used in COSI most likely.
> chore: remove `ResourceSpecWrapper` interface

- pkg/resource/protobuf/spec.go
It's copied everywhere, so we pointer receiver will fail this check:
```go
type Getter interface {
GetValue() proto.Message
}
if _, ok := wrapper.(Getter); ok {
...
}
```
> chore: use value receiver in `GetValue` method of the `ResourceSpec`

- pkg/resource/protobuf/spec.go
- pkg/resource/protobuf/spec_test.go
- pkg/resource/resource.go
When resource spec is a protobuf-generated struct, resource.Equal was
working incorrectly as proto types can't be compared correctly with
reflect.DeepEqual.
> fix: correctly compare resources when specs are embedded proto structs

- pkg/resource/protobuf/protobuf.go
- pkg/resource/protobuf/spec.go
- pkg/state/impl/store/protobuf.go
We should always use wrapper around `proto.Marshal` and
`proto.Unmarshal` to make sure vtprotobuf optimization is picked up
correctly.
> fix: refactor code to use optimized protobuf marshal

- pkg/controller/conformance/controllers.go
- pkg/controller/conformance/runtime.go
- pkg/safe/reader.go
- pkg/safe/state.go
- pkg/safe/writer.go
- pkg/state/conformance/state.go
Add typed wrappers around cosi State, Reader and Writer methods and use them.
> chore: add typed wrappers around State, Reader and Writer

- pkg/resource/protobuf/spec.go
- pkg/resource/typed/typed_resource.go
- pkg/resource/typed/typed_resource_test.go
Simplify JSON encoded resource encoding and decoding.
> chore: add `json.Marshaler/Unmarshaler` to `protobuf.ResourceSpec`

- pkg/resource/labels.go
- pkg/resource/labels_test.go
The condition was incorrect in the `labels.Match` function and we had no
test for it. Should be good now.
> fix: match `WithoutLabel` when there are no labels

- pkg/safe/state.go
- pkg/safe/state_test.go
The introduction of generics makes it possible to have watch methods
that do type assertions automatically before returning resources to the
user. We add a generic wrapper for state.{Watch, WatchFor, WatchKind}.
In case a tombstone is encountered the zero value of the expected type
is returned.
>  feat: add type safe wrappers for state.Watch* methods

- pkg/controller/protobuf/client/client.go
- pkg/controller/runtime.go
- pkg/controller/runtime/adapter.go
- pkg/controller/runtime_test.go
Now state.State might be passed in when controller.Reader is required.
There are no GetOptions now, so it's no-op and non-breaking change.
> refactor: make state.State satisfy controller.Reader interface

- pkg/resource/protobuf/spec.go
This fixes YAML marshalling for resources with protobuf spec:
```yaml
spec:
value:
foo: bar
```
becomes
```yaml
spec:
foo: bar
```
> fix: inline YAML protobuf value

- pkg/resource/typed/typed_resource.go
This allows doing something like:
```go
var r R
rd := r.ResourceDefinition()
```
> fix: allow calling ResourceDefintion on nil TypedResource

- go.mod
- go.sum
Adds the support for `uint8|int8|uint16|int16`.
> chore: bump protoenc from v0.1.1 to v0.1.2

- pkg/resource/protobuf/spec.go
Right now in some situations Go build fails with internal compiler error. This was fixed by https://go.dev/cl/421755 but until Go 1.19.1 is here we have to use this workaround.
> fix: temporary workaround for proto.Clone ICE

- pkg/state/conformance/state.go
- pkg/state/impl/inmem/local_test.go
- pkg/state/impl/namespaced/namespaced_test.go
- pkg/state/protobuf/protobuf_test.go
- pkg/state/protobuf/server/server.go
The problem was that gRPC implementation of Wait API never aborted, as
channel is never closed.
Fix that, and also add regression tests via tracing goroutine leaks in
the unit-tests.
> fix: abort the loop in gRPC implementation of Wait

- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- pkg/state/conformance/state.go
- pkg/state/impl/inmem/collection.go
- pkg/state/impl/inmem/local_test.go
- pkg/state/impl/namespaced/namespaced_test.go
- pkg/state/protobuf/protobuf_test.go
- pkg/state/protobuf/server/server.go
The problem was that gRPC implementation of Wait API never aborted, as
channel is never closed.
Fix that, and also add regression tests via tracing goroutine leaks in
the unit-tests.
(cherry picked from commit 144badf4c6b577fa992d7531cc9625da38a6cd38)
> backport: fix: abort the loop in gRPC implementation of Wait

- pkg/state/conformance/state.go
- pkg/state/impl/inmem/collection.go
Also remove conformance.StateSuite.TearDownTest method.
> fix: ensure there is no deadlock in ResourceCollection.Watch and WatchAll

- pkg/state/impl/store/encryption/marshaler.go
- pkg/state/impl/store/encryption/marshaler_test.go
This `Marshaler` is used to encrypt data that was marshaled by the underlying `store.Marshaler`.
> feat: add encryption.Marshaler

- pkg/state/impl/store/bolt/conformance_test.go
- pkg/state/impl/store/bolt/example_test.go
Use encryption.Marshaler in example and conformance test. Also update example to run on each go test invocation.
> chore: update conformance test and example with encryption.Marshaler

- go.mod
- go.sum
- pkg/controller/generic/generic.go
- pkg/controller/generic/transform/controller.go
- pkg/controller/generic/transform/options.go
- pkg/controller/generic/transform/resource_test.go
- pkg/controller/generic/transform/transform.go
- pkg/controller/generic/transform/transform_test.go
- pkg/resource/rtestutils/assertions.go
- pkg/resource/rtestutils/destroy.go
- pkg/resource/rtestutils/errors.go
- pkg/resource/rtestutils/ids.go
- pkg/resource/rtestutils/rtestutils.go
This type of controller transforms (or maps) resources of one type into resources of another type. Transformation function might have side effects which provide the additional feature.
Also additional inputs might be used to facilitate the transformation process.
Controller provides the necessary boilterplate to handle all flows with finalizers and teardown flow.
> feat: implement generic (template) transform controller

- pkg/controller/generic/transform/transform_test.go
- pkg/state/options.go
- pkg/state/protobuf/client/client.go
- pkg/state/protobuf/client/client_test.go
This allows to skip full protobuf unmarshaling and preserve the original YAML representation which is sometimes helpful when there's a goal to preserve compatibility with the server when proto definitions are not in sync.
E.g. getting only YAML representation of a resource which is not known to the client, or some fields are not supported by the client yet.
> feat: add support for no protobuf unmarshaling via gRPC

- pkg/controller/conformance/runtime.go
- pkg/state/conformance/state.go
- pkg/state/wrap.go
This fixes a bug which is at least 22 months old (from the initial implementation).
> fix: update with conflicts should return new resource

- pkg/controller/generic/transform/controller.go
- pkg/controller/generic/transform/options.go
This allows e.g. to transform only subset of inputs by labels.
> feat: provide an option to limit inputs for TransformController

- pkg/resource/protobuf/spec.go
We are using Go 1.19.2 everywhere, so there is no need for the helper function anymore.
> chore: remove generic bug workaround

- pkg/resource/protobuf/registry.go
- pkg/resource/protobuf/registry_test.go
This should be mostly backward compatible change, which removes reflect from protobuf package and speeds-up resource creation for about 20%.
Old:
```
goos: darwin
goarch: arm64
pkg: github.com/cosi-project/runtime/pkg/resource/protobuf
BenchmarkCreateResource
BenchmarkCreateResource-10    	10725361	       101.9 ns/op
PASS
```
New:
```
goos: darwin
goarch: arm64
pkg: github.com/cosi-project/runtime/pkg/resource/protobuf
BenchmarkCreateResource
BenchmarkCreateResource-10    	12643134	        85.93 ns/op
PASS
```
> refactor: redo `proto.RegisterResource` with generics

- pkg/resource/metadata.go
- pkg/resource/metadata_test.go
- pkg/resource/protobuf/yaml.go
- pkg/resource/protobuf/yaml_test.go
Adds the special wrapper type - `YAMLResource` which is used to create resources from their YAML representation. Those resources should be registered with `protobuf.RegisterResource`.
> chore: add `YAMLResource` resource wrapper

- pkg/resource/metadata.go
- pkg/state/impl/inmem/backing_store_test.go
- pkg/state/impl/inmem/collection.go
Since we now have a way to create resources from their YAML representation, we want to ensure that invariants hold. For this commit we ensure that metadata creation date is always set, and cannot be overridden even on `Update`.
> chore: add `SetCreated` to `resource.Metadata`

- pkg/controller/generic/transform/controller.go
- pkg/controller/protobuf/client/client.go
- pkg/controller/runtime.go
- pkg/controller/runtime/adapter.go
This allows controller to say that it finished the reconcile loop without errors, so the restart backoff can be reset back to the initial value.
> feat: add ResetRestartBackoff method to the controller adapter

- Dockerfile
- pkg/resource/protobuf/spec.go
- pkg/resource/protobuf/spec_test.go
`yaml:",inline"` do not play well with custom types `MarshalYAML`, so for `ResourceSpec` we have to implement it manually.
> chore: redo YAML `inline` as MarshalYAML/UnmarshalYAML instead of the field tag.

- pkg/controller/runtime/runtime_test.go
- pkg/state/impl/inmem/collection.go
- pkg/state/impl/inmem/inmem.go
- pkg/state/impl/inmem/local_test.go
- pkg/state/impl/inmem/options.go
It's now possible to set initial/max capacity of the event buffer for in-memory resource collection. The defaults are still fixed 100 entries.
Allow to optionally set dynamic capacity of the history buffer, so that for resource types which are not updated frequently less memory is wasted for the allocated event stream, while frequently updated resources might benefit from a deeper history buffer.
This should help Talos, as it has 87 different resource types (and at least each resource has its own buffer), while some resources are updated frequently, while others are almost static. We can set dynamic capacity with smaller initial capacity which will grow on demand based on the number resources created/updated.
> feat: implement dynamic sizing of history buffer for in-mem resources

- pkg/resource/finalizer.go
- pkg/resource/finalizer_test.go
Has was missing, and causing lots of trouble.
Set method allows to copy finalizers from one resource to another.
> feat: add Set/Has methods to finalizers

- pkg/controller/conformance/controllers.go
- pkg/controller/conformance/runtime.go
- pkg/controller/protobuf/client/client.go
- pkg/controller/runtime/adapter.go
This feature got broken in 1ed3207ee2808e35ea0f3a6ddbe149ed7e90223b, as named return was replaced with a variable which doesn't work to override return value in defer blocks.
In case of panic, panic was intercepted correctly, but still `nil` was returned, as panic was handled. And `nil` return means "don't restart" which stops automatic controller restarts.
> fix: restart controllers on panic

- pkg/controller/conformance/controllers.go
- pkg/controller/conformance/runtime.go
- pkg/controller/protobuf/client/client.go
- pkg/controller/runtime/adapter.go
This feature got broken in 1ed3207ee2808e35ea0f3a6ddbe149ed7e90223b, as named return was replaced with a variable which doesn't work to override return value in defer blocks.
In case of panic, panic was intercepted correctly, but still `nil` was returned, as panic was handled. And `nil` return means "don't restart" which stops automatic controller restarts.
(cherry picked from commit 62c39680d91b09d457e4c3a345e238e744cb6799)
> backport: fix: restart controllers on panic

- pkg/controller/generic/transform/controller.go
- pkg/controller/generic/transform/options.go
- pkg/controller/generic/transform/transform_test.go
This is sometimes useful for `Resource` -> `ResourceStatus` when the status resource should exist as long as the input resource exists, even if it's being torn down.
This only works if the controller doesn't set finalizers on its input, as otherwise it breaks the logic: if the finalizer is set, output should be destroyed before the input.
> feat: allow transform controller to ignore tearing down inputs

- pkg/controller/generic/transform/resource_test.go
- pkg/resource/meta/namespace.go
- pkg/resource/meta/resource_definition.go
- pkg/resource/protobuf/spec_test.go
- pkg/resource/protobuf/yaml_test.go
- pkg/resource/typed/typed_resource.go
- pkg/resource/typed/typed_resource_test.go
- pkg/state/impl/store/bolt/example_test.go
This commit allows us to define and use custom methods on renamed `ResourceDefinition` -> `Extension` type.
> chore: extension methods for typed.Resource, simplify ResourceDefinition

- pkg/resource/typed/typed_resource.go
There is no reason for `Extension` to be typed anymore.
> fix: drop unused type parameter from typed.Extension type

- go.mod
- go.sum
- pkg/state/impl/store/compression/compression.go
- pkg/state/impl/store/compression/compression_test.go
- pkg/state/impl/store/compression/zstd.go
It is backwards compatible (i.e. it can read uncompressed resources), and it has a minimum size to be enabled.
This should help a lot with resources which have compressible data.
> feat: implement compressed resource marshaling

- pkg/state/impl/store/compression/compression_test.go
- pkg/state/impl/store/compression/zstd.go
This commit drastically decreases memory consumption in some cases.
> chore: pass compression options to `zstd.Encoder`

- pkg/state/impl/inmem/inmem.go
Just small beautification/clarification.
> chore: replace `loaded` uint64 with atomic.Bool

- .github/workflows/ci.yml
- Dockerfile
Bump deps:
- docker.io/node to 20.2.0-alpine3.17
- codecov-action to v3.1.4
> chore: bump deps

- pkg/safe/state.go
- pkg/safe/state_test.go
This allows to fetch resource list once and filter it many times.
> feat: implement label query filter on safe.List

- pkg/controller/protobuf/server/server.go
- pkg/internal/xutil/sync_map.go
- pkg/state/impl/inmem/inmem.go
- pkg/state/impl/namespaced/namespaced.go
Alternative to #274 - this PR adds typesafe wrapper around sync.Map. The main benefit is that we can drop it, once generic version of sync.Map arrives.
> chore: add type-safe wrapper around sync.Map

- pkg/internal/xutil/sync_map.go
- pkg/internal/xutil/sync_map_test.go
For some reason, previous PR didn't get updated during push. This commit fixes problems with previous implementation and adds tests.
> fix: proper type assertions in xutils.SyncMap

- pkg/controller/generic/generic.go
- pkg/resource/meta/resource_definition.go
- pkg/resource/rtestutils/rtestutils.go
- pkg/state/registry/resource.go
Also, `ResourceRegistry.Register` now accepts `meta.ResourceWithRD` instead of plain `resource.Resource`. This removes the need for type assertion.
> chore: unify all ResourceWithRD as an alias to meta.ResourceWithRD

- pkg/resource/labels.go
- pkg/resource/labels_test.go
Introduce `nil` value which is never true, even if `invert` is set on the term.
`nil` is returned when parsing string to number fails on the label value or on the term value.
> fix: properly invert numeric < and <= operators

- pkg/resource/label_query.go
- pkg/resource/labels.go
- pkg/resource/labels_test.go
Should return `nil` if the key doesn't exist in the labels.
> fix: properly handle invert for comparison, when key not found

- pkg/controller/generic/transform/controller.go
- pkg/controller/generic/transform/options.go
- pkg/controller/generic/transform/resource_test.go
- pkg/controller/generic/transform/transform_test.go
Add an option to specify an extra channel to the transform controller. Controller will wake up upon receiving data from the channel and run transform.
> feat: add extra channel support to transform controller

- pkg/resource/rtestutils/destroy.go
If some other entity cleans up torn down resources, `rtestutils.Destroy` might fail trying to destroy already destroyed resource.
Fix that by ignoring 'not found' errors on destroy.
> test: ignore not found when destroying in rtestutils

- pkg/resource/metadata.go
- pkg/resource/metadata_test.go
It might be pretty common to have 1-2 finalizers, so we can do a special case for it.
```
name                old time/op    new time/op    delta
MetadataEqual/0-32    12.1ns ± 2%    11.8ns ± 2%      ~     (p=0.057 n=4+4)
MetadataEqual/1-32     206ns ± 8%      14ns ± 0%   -93.11%  (p=0.029 n=4+4)
MetadataEqual/2-32     268ns ± 7%      21ns ± 2%   -92.13%  (p=0.029 n=4+4)
MetadataEqual/3-32     328ns ± 4%     227ns ± 4%   -30.86%  (p=0.029 n=4+4)
name                old alloc/op   new alloc/op   delta
MetadataEqual/0-32     0.00B          0.00B           ~     (all equal)
MetadataEqual/1-32     80.0B ± 0%      0.0B       -100.00%  (p=0.029 n=4+4)
MetadataEqual/2-32      112B ± 0%        0B       -100.00%  (p=0.029 n=4+4)
MetadataEqual/3-32      144B ± 0%       96B ± 0%   -33.33%  (p=0.029 …
```
> refactor: optimize the metadata.Equal for small number of finalizers

- pkg/resource/rtestutils/assertions.go
- pkg/resource/rtestutils/errors.go
Instead of reporting on every watch event, report every 30 seconds.
> test: throttle down rtestutils reports

- cmd/runtime/main.go
- pkg/controller/runtime/adapter.go
- pkg/controller/runtime/metrics/metrics.go
Expose:
- controller crashes
- controller wakeups
- controller reads
- controller writes
using the expvar package.
Closes cosi-project/runtime#344.
Example output from the `/debug/vars` endpoint:
```json
{
"cmdline": ["/Users/utku/Library/Caches/JetBrains/GoLand2023.2/tmp/GoLand/___run_inmem","--grpc-address=127.0.0.1:8181","--http-address=127.0.0.1:8182"],
"controller_crashes": {"IntToStrController": 6},
"controller_reads": {"IntToStrController": 11},
"controller_wakeups": {"IntToStrController": 11},
"controller_writes": {"IntToStrController": 36},
"memstats": {"Alloc":1147736,"TotalAlloc":1147736,"Sys":8031248,"Lookups":0,"Mallocs":6876,"Frees":335,"HeapAlloc":1147736,"HeapSys":3604480,"HeapIdle":1425408,"HeapInuse":2179072,"HeapReleased":1425408,"HeapObjects":6541,"StackInuse":589824,"S …
```
> feat: expose controller metrics using `expvar`

- pkg/controller/conformance/controllers.go
- pkg/controller/conformance/runtime.go
- pkg/controller/protobuf/client/client.go
- pkg/controller/runtime.go
- pkg/controller/runtime/adapter.go
- pkg/safe/reader.go
- pkg/safe/safe.go
- pkg/safe/state.go
- pkg/safe/writer.go
Add a new method, `ModifyWithResult` to the `controller.Writer` interface. This is the equivalent of `state.UpdateWithConflicts`, which returns the created/updated resource after the operation.
Also add its safe variant, `safe.WriterModifyWithResult`.
> feat: add `ModifyWithResult` to `controller.Writer` interface

- cmd/runtime/main.go
- pkg/controller/conformance/controllers.go
- pkg/controller/conformance/runtime.go
- pkg/controller/protobuf/protobuf_test.go
- pkg/controller/runtime/adapter.go
- pkg/controller/runtime/metrics/state.go
- pkg/controller/runtime/options.go
Instead of incrementing the metrics on each call to read or write, wrap the underlying state and increment the metric counters only when a `CoreState` operation succeeds.
Make it possible to disable metrics in runtime.
> feat: rework controller read/write metrics

- pkg/safe/state.go
Somehow I missed those during the last update.
> chore: replace `State` with `CoreState` in `safe.StateWatch` and `safe.StateWatchKind`.

- pkg/controller/generic/cleanup/cleanup.go
- pkg/controller/generic/cleanup/cleanup_test.go
This should reduce a lot number of wakeups of the `CleanupController` when it shouldn't actually do any work.
As the controller in RemoveOutputs mode always tearsdown and destroy all outputs owned by configured owner, it is only interested in the moment the output has no finalizers left.
Improve the tests to actually verify the cleanup with finalizers.
Fix typos.
> fix: use destroy ready input type in CleanupController

- pkg/controller/runtime/internal/qruntime/internal/queue/queue.go
If we always push with zero timestamp, there's a chance that items with non-zero timestamp (e.g. items pushed with some backoff) will never be processed at all, as they will stay at the tail of the queue, and the head of the queue will be occupied with items with zero timestamp.
With this change, new items without backoff are pushed with timestamp `now`, so they will be properly ordered with other items.
> fix: push to queue with non-zero timestamp

- .codecov.yml
- .kres.yaml
- pkg/controller/generic/qtransform/qtransform.go
- pkg/controller/generic/qtransform/qtransform_test.go
The controller should unwrap the error to allow `Modify` call to succeed, but it should re-wrap it back into RequeueError when returning to qruntime.
> fix: pass through correctly requeue errors via qtransform

- pkg/resource/handle/handle.go
- pkg/resource/handle/handle_test.go
This commit adds a new package named 'handle', designed for managing resources that are descriptors or handles. These handles are restricted from being transmitted from client to server. The unmarshalling of these resources is also disabled.
> chore: implement "handle-like" resources

- pkg/controller/runtime/internal/qruntime/qruntime.go
When the full logs were enabled, it wasn't clear which logs we need and which we don't. These 'job: map' events are very noisy, and give little context if I'm not debugging some weird issue that something wasn't triggered (and even if I do, these logs might be not enough).
So make them 'debug' for now to reduce the noise.
New logs:
```
logger.go:130: 2024-02-06T18:44:51.575+0400 INFO    reconcile succeeded     {"controller": "QIntToStrController", "namespace": "q-int", "type": "test/int", "id": "id1", "job": "reconcile", "busy": "25.427µs"}
logger.go:130: 2024-02-06T18:44:51.575+0400 DEBUG   reconcile succeeded     {"controller": "QIntToStrController", "namespace": "q-str", "type": "test/str", "id": "id1", "job": "map", "busy": "3.457µs"}
```
The first line is normal reconcile, the second …
> chore: hide "map" job reconcile events under the debug

- pkg/controller/runtime/internal/qruntime/internal/containers/priority_queue.go
- pkg/controller/runtime/internal/qruntime/internal/containers/priority_queue_test.go
If the controller returns `RequeueError` it should not schedule another update for a later time if there already is a task in the queue to be executed earlier.
> fix: make `RequeueError` never push existing items execution time

- pkg/controller/conformance/qcontrollers.go
- pkg/controller/conformance/runtime.go
- pkg/controller/runtime.go
- pkg/controller/runtime/internal/cache/cache.go
- pkg/controller/runtime/internal/cache/cache_test.go
- pkg/controller/runtime/internal/cache/handler.go
- pkg/controller/runtime/internal/controllerstate/adapter.go
- pkg/controller/runtime/runtime_test.go
- pkg/state/conformance/state.go
- pkg/state/state.go
- pkg/state/wrap.go
It allows to bind a context lifetime to the lifetime of a resource, so that a context is cancelled whenever a resource is destroyed or torn down.
The implementation starts with State, and then goes into the controller runtime.
In the cache of cached resource view, the method gets a new implementation.
> feat: implement ContextWithTeardown method

- pkg/controller/generic/cleanup/cleanup_test.go
- pkg/controller/generic/destroy/destroy.go
- pkg/controller/generic/destroy/destroy_test.go
For resources not owned by any controller allow using the controller that will destroy resources which have no finalizers.
> feat: implement resource self-destroy controller

- pkg/state/protobuf/server/server.go
Cancel the context sent to Watch() API in any case.
> fix: cancel the Watch context in gRPC stream

- pkg/state/impl/inmem/inmem.go
- pkg/state/impl/namespaced/namespaced.go
Use in `inmem` and `namespaced` packages.
Closes #455
> chore: replace sync.Map with HashTrieMap

- pkg/controller/generic/qtransform/qtransform.go
- pkg/controller/generic/qtransform/qtransform_test.go
If the output does not exist at all, the `Teardown` call will fail. Handle this case by checking the error.
> fix: handle non-existent output on `DestroyOutputTag`

- pkg/controller/qcontroller.go
- pkg/controller/runtime.go
- pkg/controller/runtime/internal/controllerstate/adapter.go
Usually all reads are cached, and that cache is consistent with the watch stream and controller notifications. The cache is eventually consistent (it will catch up and notification will be delivered).
But sometimes controllers make decisions which are not reconcilable back when the cache catches up. One of the case was in Omni with automatic scaling: the controller might try to scale up the same machine set twice, and it might succeed to do so, but at the same time there's no good way sometimes to "reconcile back", as scale down is not symmetric with scale up (additional pre-checks).
> feat: provide an option to skip cache on reads in the controller

- .github/workflows/ci.yml
- go.mod
- go.sum
- pkg/controller/runtime/runtime.go
Bump those things:
- actions/checkout to v4.1.2
- codecov/codecov-action to v4.1.0
- github.com/klauspost/compress v1.17.8
- google.golang.org/protobuf v1.34.1
And remove lock around `runtime.(*Runtime).group.Wait` call.
> chore: bump deps and remove false lock

- pkg/controller/generic/transform/transform_test.go
Sometimes Input event channel can be triggered more than one time. We should account for that.
> fix: update flaky TestHooks test

- pkg/task/runner.go
- pkg/task/runner_test.go
- pkg/task/task.go
- pkg/task/task_test.go
Pull the generic task runner used in Omni (https://github.com/siderolabs/omni/tree/85424da98eed1a8c49d39e7d51d57583d607e40b/internal/backend/runtime/omni/controllers/omni/internal/task) into the runtime.
> feat: add generic task runner

- pkg/resource/rtestutils/assertions.go
- pkg/safe/state.go
- pkg/safe/util.go
• Add `Swap` method to the `safe.List` type, so it can be sorted in place. 
• Add `ToSlice` function which converts `safe.List` to slice using the provided function.
> chore: add two functions to the `safe` package

- pkg/controller/generic/cleanup/cleanup.go
We shouldn't care if the resource doesn't exist if we're trying to destroy it.
> fix: ignore output not found errors in the cleanup controller

- pkg/controller/generic/cleanup/cleanup.go
Otherwise it accumulates the backoff forever.
> fix: call reset backoff in the cleanup controller

- pkg/controller/generic/qtransform/qtransform.go
- pkg/controller/generic/transform/controller.go
- pkg/state/errors.go
- pkg/state/impl/inmem/errors.go
- pkg/state/impl/inmem/errors_test.go
- pkg/state/protobuf/client/client.go
- pkg/state/protobuf/client/errors.go
Fix `qtransform` controller bug which was skipping the reconciliation if the conflict error is returned from the `transformFunc` and is related to the extra outputs.
Introduce a way to check if the error was raised by any particular resource type.
> fix: skip update only if the conflict error is related to main output

- go.mod
- go.sum
- pkg/state/protobuf/client/client.go
- pkg/state/protobuf/protobuf_test.go
There were two bugs:
* `io.EOF` was ignored for no good reason
* the aggregated/non-aggregated was not properly handled for errors
This should fix COSI controller runtime not crashing on connection close via gRPC.
> fix: abort watch correctly for protobuf client

- pkg/state/conformance/state.go
Don't share resource Metadata() between watch goroutine and tests.
> test: fix a data race in the test

- pkg/controller/generic/qtransform/options.go
The namespace should be taken from the output resource definition, not from the input metadata.
> fix: correctly map resources with differrent ns in `MapperSameID`

- pkg/state/errors.go
- pkg/state/impl/inmem/collection.go
- pkg/state/impl/inmem/errors.go
- pkg/state/impl/inmem/errors_test.go
- pkg/state/impl/inmem/local_test.go
- pkg/state/protobuf/client/client.go
- pkg/state/protobuf/client/errors.go
- pkg/state/protobuf/protobuf_test.go
- pkg/state/protobuf/server/server.go
As inmem storage is not persisted, make sure watch bookmark from one run doesn't work with another run.
This still allows watches to be restarted on connection failures, but if the watch is restarted on a program restart, bookmark won't match anymore.
> fix: make inmem bookmarks random for each run

- pkg/state/protobuf/client/client.go
It suppresses logging and returns a bit earlier (mostly cosmetic fix).
> fix: don't report that we retry context canceled

- pkg/state/conformance/state.go
- pkg/state/options.go
- pkg/state/state.go
- pkg/state/wrap.go
The function combines `Teardown`, `Watch` for finalizers to be empty and `Destroy` calls.
Fixes: https://github.com/siderolabs/omni/issues/1137
> feat: implement `TeardownAndDestroy` helper function

- pkg/safe/util.go
For these two methods it actually makes sense to have any return type there.
> fix: allow any type in the `safe.ToSlice` and `safe.Map` methods

- pkg/resource/rtestutils/assertions.go
Fix two things in the resource asserters:
1. We were doing a busy `state.Get` loop in the resource assertions. This was unnecessary to wait for a resource to be created, as we also create a watch, and the moment the resource gets created, we get notified. Changed this logic to follow the same logic with the rest of the assertions on the resource (block on `watch` events).
2. This busy wait also produced a test log every single time the resource was not found, producing an excessive number of logs. Remove this log and unify the logic with the rest of the assertions (see fix 1), so that the NotFound logs will also be aggregated/de-duplicated.
> fix: fix resource assertion logic and its logging

- pkg/controller/runtime/runtime.go
When the watch is established in the controller runtime after the runtime starts, make sure watch asks for the initial bookmark, so that the watch can be restarted on connection failure.
> fix: set initial watch bookmark on "late watches"
